export const DEPLOY_CONTRACT_REQUEST = 'DEPLOY_CONTRACT_REQUEST'
export const DEPLOY_CONTRACT_SUCCESS = 'DEPLOY_CONTRACT_SUCCESS'
export const DEPLOY_CONTRACT_FAILURE = 'DEPLOY_CONTRACT_FAILURE'

export const WATCH_CONTRACT_REQUEST = 'WATCH_CONTRACT_REQUEST'
export const WATCH_CONTRACT_SUCCESS = 'WATCH_CONTRACT_SUCCESS'
export const WATCH_CONTRACT_FAILURE = 'WATCH_CONTRACT_FAILURE'

export const FETCH_OWNER_REQUEST = 'FETCH_OWNER_REQUEST'
export const FETCH_OWNER_SUCCESS = 'FETCH_OWNER_SUCCESS'
export const FETCH_OWNER_FAILURE = 'FETCH_OWNER_FAILURE'
