import { EVENT } from '../../services/utils'

export const FETCH_PLATFORM_STATUS_REQUEST = 'FETCH_PLATFORM_STATUS_REQUEST'
export const FETCH_PLATFORM_STATUS_SUCCESS = 'FETCH_PLATFORM_STATUS_SUCCESS'
export const FETCH_PLATFORM_STATUS_FAILURE = 'FETCH_PLATFORM_STATUS_FAILURE'

export const OPEN_PLATFORM_REQUEST = 'OPEN_PLATFORM_REQUEST'
export const OPEN_PLATFORM_SUCCESS = 'OPEN_PLATFORM_SUCCESS'
export const OPEN_PLATFORM_FAILURE = 'OPEN_PLATFORM_FAILURE'

export const CLOSE_PLATFORM_REQUEST = 'CLOSE_PLATFORM_REQUEST'
export const CLOSE_PLATFORM_SUCCESS = 'CLOSE_PLATFORM_SUCCESS'
export const CLOSE_PLATFORM_FAILURE = 'CLOSE_PLATFORM_FAILURE'

export const PLATFORM_STATUS_CHANGED = EVENT('PlatformStatus')
